os: linux
dist: bionic 

language: 
    - c

before_install:
    - pip install --user cpp-coveralls
    
addons:
  sonarcloud:
    organization: "kuuselaaaaa"
    token: $SONAR
    
script:
    - qmake
    - make
    - ./tests/tests
    
after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"    
    
notification:
    email: false

